#!/usr/bin/env just --justfile

_default:
    @just --list

sample-1:
	#!/usr/bin/env nu
	let actual = nu 01.script.nu 01.sample-1.txt
	let expected = "0,0,3,3,3,-1,-1,-3,-3"
	echo "expected" $expected "actual:" $actual "" passed: ($actual == $expected)

puzzle-1:
	#!/usr/bin/env nu
	let actual = nu 01.script.nu 01.input.txt
	let expected = "280"
	echo "expected" $expected "actual:" $actual "" passed: ($actual == $expected)

sample-2:
	#!/usr/bin/env nu
	let actual = nu 02.script.nu 01.sample-2.txt
	let expected = "1,5"
	echo "expected" $expected "actual:" $actual "" passed: ($actual == $expected)

puzzle-2:
	#!/usr/bin/env nu
	let actual = nu 02.script.nu 01.input.txt
	let expected = "1797"
	echo "expected" $expected "actual:" $actual "" passed: ($actual == $expected)
